# -*- coding: utf-8 -*-
"""1 Combine Synetica by year.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bKlZH6kSLNo2rGb4dWzmFyr0Y0g9I00U
"""

from google.colab import drive
drive.mount("/content/gdrive")

import pandas as pd

#combine 2018 data

jan = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-jan-2018.csv')
feb = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-feb-2018.csv')
mar = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-mar-2018.csv')
apr = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-apr-2018.csv')
may = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-may-2018.csv')
jun = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-jun-2018.csv')
jul = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-jul-2018.csv')
aug = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-aug-2018.csv')
sep = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-sep-2018.csv')
oct = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-oct-2018.csv')
nov = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-nov-2018.csv')
dec = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-dec-2018.csv')

all_2018 = pd.concat([jan, feb, mar, apr, may, jun, jul, aug, sep, oct, nov, dec])
all_2018.to_csv( "all_2018.csv", index=False, encoding='utf-8-sig')

#combine 2019 data

jan = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-jan-2019.csv')
feb = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-feb-2019.csv')
mar = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-mar-2019.csv')
apr = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-apr-2019.csv')
may = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-may-2019.csv')
jun = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-jun-2019.csv')
jul = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-jul-2019.csv')
aug = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-aug-2019.csv')
sep = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-sep-2019.csv')
oct = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-oct-2019.csv')
nov = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-nov-2019.csv')
dec = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-dec-2019.csv')

all_2019 = pd.concat([jan, feb, mar, apr, may, jun, jul, aug, sep, oct, nov, dec])
all_2019.to_csv( "all_2019.csv", index=False, encoding='utf-8-sig')

#combine 2020 data

jan = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-jan-2020.csv')
feb = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-feb-2020.csv')
mar = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-mar-2020.csv')
apr = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-apr-2020.csv')
may = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-may-2020.csv')
jun = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-jun-2020.csv')
jul = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-jul-2020.csv')
aug = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-aug-2020.csv')
sep = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-sep-2020.csv')
oct = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-oct-2020.csv')
nov = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-nov-2020.csv')
dec = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-dec-2020.csv')

all_2020 = pd.concat([jan, feb, mar, apr, may, jun, jul, aug, sep, oct, nov, dec])
all_2020.to_csv( '/content/gdrive/My Drive/data/Synetica/all_2020.csv', index=False, encoding='utf-8-sig')

columns = ['timestamp', 'name', 'reading', 'units']
df2020 = pd.read_csv('/content/gdrive/My Drive/data/Synetica/all_2020.csv', usecols=columns)
df2020.head()

df2020.units.describe()

df2020KWh = df2020[df2020["units"] == "KWh"]
df2020KWh.head()

df2020KWh.shape

columns = ['timestamp', 'name', 'reading', 'units']
df = pd.read_csv('/content/gdrive/My Drive/data/Synetica/synetica-mar-2018.csv', usecols=columns)
df.reading.describe()

jan = pd.read_csv('/content/gdrive/My Drive/data/Synetica/all_2020.csv')
jan.head()

!python --version