# -*- coding: utf-8 -*-
"""2 Split year into name Synetica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mh6mzw6akRA5Gvdn_1OVdn8O5S-9LdvU
"""

from google.colab import drive
drive.mount("/content/gdrive")

import pandas as pd

#changing / to _ and splitting df by name for 2018 data
df = pd.read_csv('/content/gdrive/My Drive/data/Synetica/all_2018.csv')
df2 = df.replace('/', '_', regex=True)

for name, value in df2.groupby('name'):
    value.to_csv('/content/gdrive/My Drive/data/Synetica/meters_2018/'f'{name}.csv')

#changing / to _ and splitting df by name for 2019 data
df = pd.read_csv('/content/gdrive/My Drive/data/Synetica/all_2019.csv')
df2 = df.replace('/', '_', regex=True)

for name, value in df2.groupby('name'):
    value.to_csv('/content/gdrive/My Drive/data/Synetica/meters_2019/'f'{name}.csv')

#changing / to _ and splitting df by name for 2020 data
df = pd.read_csv('/content/gdrive/My Drive/data/Synetica/all_2020.csv')
df2 = df.replace('/', '_', regex=True)

for name, value in df2.groupby('name'):
    value.to_csv('/content/gdrive/My Drive/data/Synetica/meters_2020/'f'{name}.csv')