# -*- coding: utf-8 -*-
"""3 unique readings and merge with meta file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1if9ZMtslCR7Wb_cUMiJ6KVX8ALuOIeRt
"""

from google.colab import drive
drive.mount("/content/gdrive")

import pandas as pd
import glob

# Create new CSV with nunique values and meter name. Not sure how to save this print output as a .csv,
# so make a new .txt file with the output from this cell, add meter id and unique column names, copy paste output and upload new 'unique.csv' to drive
fields = ['reading']
both = ['reading', 'name']
path = "/content/gdrive/My Drive/data/Synetica/meters_2019/*.csv"
for fname in glob.glob(path):
   df=pd.read_csv(fname, usecols=both)
   unique_readings=list(df[fields].nunique())
   if unique_readings:
    print(df['name'][0], unique_readings[0], sep=',', end=',\n')

#Merge new unique.csv with meta
df = pd.read_csv('/content/gdrive/My Drive/data/Synetica/meter_list.csv')
df_unique = pd.read_csv('/content/gdrive/My Drive/data/Synetica/unique.csv', index_col=False)

df_unique = df_unique.replace('_', '/', regex=True)

meta = df.join(df_unique.set_index('Meter ID'), on='Meter ID')
meta.to_csv('/content/gdrive/My Drive/data/Synetica/meta.csv')

meta = pd.read_csv('/content/gdrive/My Drive/data/Synetica/meta.csv')

#Sort by type,rate and highest nunique readings

meta = meta.loc[(meta['Meter Type'] == 'Heat') & (meta['class'] == 'Rate')]# & (meta['serving_revised'] != 'Sub station')]
meta = meta.replace('/', '_', regex=True)

meta = meta.sort_values(by=['nunique'], ascending=False)

meta.iloc[0:30]