# -*- coding: utf-8 -*-
"""6.2 LSTM day.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VPwMrg1Re66ySgUhCnFf2pX4AWpghBjT
"""

from google.colab import drive
drive.mount("/content/gdrive")

import numpy
import matplotlib
matplotlib.rc('figure', figsize=(30, 10))
import matplotlib.pyplot as plt
import pandas as pd
import math
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

# load the dataset
dataframe = pd.read_csv('/content/gdrive/My Drive/data/Synetica/meters_final/30min/MC078-L02_M3format30min.csv', usecols=[1], engine='python')
dataset = dataframe.values[0:720]
dataset = dataset.astype('float32')

dataset.mean()

# fix random seed for reproducibility
numpy.random.seed(7)

# normalize the dataset
scaler = MinMaxScaler(feature_range=(0, 1))
dataset = scaler.fit_transform(dataset)

# split into train and test sets
train_size = int(len(dataset) * 0.933333)
test_size = len(dataset) - train_size
train, test = dataset[0:train_size,:], dataset[train_size:len(dataset),:]
print(len(train), len(test))

# convert an array of values into a dataset matrix
def create_dataset(dataset, look_back=1):
	dataX, dataY = [], []
	for i in range(len(dataset)-look_back-1):
		a = dataset[i:(i+look_back), 0]
		dataX.append(a)
		dataY.append(dataset[i + look_back, 0])
	return numpy.array(dataX), numpy.array(dataY)

# reshape into X=t and Y=t+1
look_back = 1
trainX, trainY = create_dataset(train, look_back)
testX, testY = create_dataset(test, look_back) 

# reshape input to be [samples, time steps, features]
trainX = numpy.reshape(trainX, (trainX.shape[0], 1, trainX.shape[1]))
testX = numpy.reshape(testX, (testX.shape[0], 1, testX.shape[1]))

# create and fit the LSTM network
model = Sequential()
model.add(LSTM(4, input_shape=(1, look_back)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(trainX, trainY, epochs=60, batch_size=2, verbose=2)

#calculate aic for regression
def calculate_aic(n, mse, num_params):
	aic = n * math.log(mse) + 2 * num_params
	return aic
#calculate bic for regression
def calculate_bic(n, mse, num_params):
	bic = n * math.log(mse) + num_params * math.log(n)
	return bic

# make predictions
trainPredict = model.predict(trainX)
testPredict = model.predict(testX)
# invert predictions
trainPredict = scaler.inverse_transform(trainPredict)
trainY = scaler.inverse_transform([trainY])
testPredict = scaler.inverse_transform(testPredict)
testY = scaler.inverse_transform([testY])

print('DAY RESULTS')

#calculate the mean squared error
MSEtrainScore = mean_squared_error(trainY[0], trainPredict[:,0])
print('Train Score: %.5f MSE' % (MSEtrainScore))
MSEtestScore = mean_squared_error(testY[0], testPredict[:,0])
print('Test Score: %.5f MSE' % (MSEtestScore))
#calculate root mean squared error
trainScore = math.sqrt(mean_squared_error(trainY[0], trainPredict[:,0]))
print('Train Score: %.5f RMSE' % (trainScore))
testScore = math.sqrt(mean_squared_error(testY[0], testPredict[:,0]))
print('Test Score: %.5f RMSE' % (testScore))
#calculate the train aic
aic = calculate_aic(len(testY[0]), MSEtrainScore, len(test))
print('Train AIC: %.5f' % aic)
#calculate the train bic
bic = calculate_bic(len(testY[0]), MSEtrainScore, len(test))
print('Train BIC: %.5f' % bic)
#calculate the test aic
aic = calculate_aic(len(testY[0]), MSEtestScore, len(test))
print('Test AIC: %.5f' % aic)
#calculate the test bic
bic = calculate_bic(len(testY[0]), MSEtestScore, len(test))
print('Test BIC: %.5f' % bic)

# shift train predictions for plotting
trainPredictPlot = numpy.empty_like(dataset)
trainPredictPlot[:, :] = numpy.nan
trainPredictPlot[look_back:len(trainPredict)+look_back, :] = trainPredict
# shift test predictions for plotting
testPredictPlot = numpy.empty_like(dataset)
testPredictPlot[:, :] = numpy.nan
testPredictPlot[len(trainPredict)+(look_back*2)+1:len(dataset)-1, :] = testPredict
# plot baseline and predictions
plt.plot(scaler.inverse_transform(dataset), label='raw data')
plt.plot(trainPredictPlot, label='train prediction', color = 'green')
plt.plot(testPredictPlot, label='test prediction', color = 'red')
plt.title("MC078-L02_M3 Day Forecast",fontsize=18)
plt.ylabel("Reading Water(m3))",fontsize=16)
plt.yticks(fontsize=14)
leg = plt.legend()
plt.show()

#plot just test and prediction
plt.plot(testPredict, label='test prediction', color = 'red')
plt.plot(scaler.inverse_transform(test), label='raw test data', color='blue')
plt.title("MC078-L02_M32 Day Forecast",fontsize=18)
plt.ylabel("Reading Water (m3)",fontsize=16)
plt.yticks(fontsize=14)
leg = plt.legend()
plt.show()